version: '3.4'

services:
  mysqltest:
    image: ${DOCKER_REGISTRY-}mysqltest
    build:
      context: .
      dockerfile: MySqlTest/Dockerfile


  docker.mysql:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /usr/mysql:/var/lib/mysql
    networks:
      - docker-net

  mysqltest:
    image: registry.cn-hangzhou.aliyuncs.com/mhw-hubs/mysqltest
    restart: always
    depends_on:
      - docker.mysql
    networks:
      - docker-net

  docker.nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - mysqltest
    networks:
      - docker-net

networks:
  docker-net:
    driver: bridge