@baseUrl = http://localhost:5000
# 测试
### 测试是否正常启动
GET {{baseUrl}}/api/values HTTP/1.1

### 获取商户数据
GET {{baseUrl}}/api/business/get HTTP/1.1

### 获取员工数据
GET {{baseUrl}}/api/employee/get HTTP/1.1

### 修改员工数据
POST {{baseUrl}}/api/employee/save HTTP/1.1
Content-Type: application/json

{
  "businessId": "bacced16-e7c4-4493-9ce0-b2e042c7e4e6",
  "no": "001",
  "name": "管理员",
  "mobileNo": "13934238919",
  "id": "8e7f133a-856b-44da-80d6-3e7cd0a2510a",
  "status": 0,
  "rowFlag": "CNaubk4pgZI=",
  "lastChange": "2019-03-22T10:30:12.084617",
  "isChanged": false,
  "memo": null
}

